# Generated by Django 4.1.4 on 2022-12-29 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.ImageField(blank=True, default='post_images/giant_cat.png', upload_to='media/post_images')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, default='post_images/giant_cat.png', upload_to='project_images')),
                ('code_snippet', models.TextField(blank=True)),
                ('code_snippet_is_html', models.BooleanField(default=False, verbose_name='Already HTML?')),
                ('github_url', models.URLField(blank=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section_template', models.CharField(choices=[('CF', 'CONTENT_FULL'), ('IR', 'IMAGE_RIGHT'), ('IL', 'IMAGE_LEFT'), ('TX', 'PURE_TEXT'), ('CD', 'PURE_CODE'), ('HT', 'PURE_HTML')], default='CF', max_length=2)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('content_is_html', models.BooleanField(default=False, verbose_name='Already HTML?')),
                ('image_url', models.ImageField(blank=True, upload_to='media/project_images')),
                ('image_description', models.CharField(blank=True, max_length=300)),
                ('customCSS', models.FileField(blank=True, upload_to='media/customCSS')),
                ('use_customCSS', models.BooleanField(default=False, verbose_name='use custom CSS?')),
                ('code_snippet', models.TextField(blank=True)),
                ('code_snippet_is_html', models.BooleanField(default=False, verbose_name='Already HTML?')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
