# Generated by Django 4.1.4 on 2022-12-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_resume_resumesection_resumesectionobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.resume'),
        ),
        migrations.AlterField(
            model_name='resumesectionobject',
            name='resume_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_objects', to='website.resumesection'),
        ),
    ]
