# Generated by Django 4.1.4 on 2022-12-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(upload_to='media/post_images'),
        ),
    ]
