# Generated by Django 4.1.4 on 2022-12-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_projects_alter_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.ImageField(null=True, upload_to='media/post_images')),
                ('code_snippet', models.TextField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
