# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_resumesection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesection',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='media/resume_images'),
        ),
    ]
