# Generated by Django 4.1.4 on 2022-12-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_project_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, default='media/post_images/giant_cat.png', upload_to='media/post_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank=True, default='media/post_images/giant_cat.png', upload_to='media/post_images'),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('opt3', 'code_section'), ('opt2', 'text_section'), ('opt1', 'image_section'), ('opt5', 'html_section'), ('opt4', 'sub_section')], default='opt1', max_length=4)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, upload_to='media/project_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
