# Generated by Django 4.1.4 on 2022-12-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_resumesection_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
