# Generated by Django 4.1.4 on 2022-12-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_post_image_url_alter_project_code_snippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_snippet_is_html',
            field=models.BooleanField(default=False, verbose_name='Already HTML?'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('opt1', 'image_section'), ('opt2', 'text_section'), ('opt5', 'html_section'), ('opt4', 'sub_section'), ('opt3', 'code_section')], default='opt1', max_length=4),
        ),
    ]
