# Generated by Django 4.1.4 on 2022-12-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_projectsection_section_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsection',
            name='image_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_template',
            field=models.CharField(choices=[('IL', 'IMAGE_LEFT'), ('CF', 'CONTENT_FULL'), ('IR', 'IMAGE_RIGHT')], default='CF', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('opt2', 'text_section'), ('opt4', 'sub_section'), ('opt3', 'code_section'), ('opt1', 'image_section'), ('opt5', 'html_section')], default='opt1', max_length=4),
        ),
    ]
