# Generated by Django 4.1.4 on 2022-12-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_projectsection_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank=True, default='media/post_images/giant_cat.png', upload_to='media/project_images'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('opt1', 'image_section'), ('opt2', 'text_section'), ('opt3', 'code_section'), ('opt5', 'html_section'), ('opt4', 'sub_section')], default='opt1', max_length=4),
        ),
    ]
