# Generated by Django 4.1.4 on 2022-12-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_project_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank=True, default='media/post_images/giant_cat.png', upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='customCSS',
            field=models.FileField(blank=True, upload_to='ustomCSS'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_template',
            field=models.CharField(choices=[('IR', 'IMAGE_RIGHT'), ('IL', 'IMAGE_LEFT'), ('CF', 'CONTENT_FULL')], default='CF', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_type',
            field=models.CharField(choices=[('opt4', 'sub_section'), ('opt1', 'image_section'), ('opt2', 'text_section'), ('opt3', 'code_section'), ('opt5', 'html_section')], default='opt1', max_length=4),
        ),
    ]
