# Generated by Django 4.1.4 on 2022-12-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_post_image_url_alter_project_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsection',
            name='section_type',
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='section_template',
            field=models.CharField(choices=[('CF', 'CONTENT_FULL'), ('IR', 'IMAGE_RIGHT'), ('IL', 'IMAGE_LEFT'), ('TX', 'PURE_TEXT'), ('CD', 'PURE_CODE'), ('HT', 'PURE_HTML')], default='CF', max_length=2),
        ),
    ]
